#!/usr/bin/env python3
"""Render manuscript Fig 3 (cross-material benchmark heatmaps).

Reads ``benchmark_metrics.csv`` from ``data/processed/`` and writes
``fig03_summary_heatmaps.png`` into ``figures/main/``. The manuscript
figure is composed from this render.

Layout: 1x3 (RMSE, NRMSE, R^2) with Arial, cell-annotated heatmaps.

Upstream of this script:
  - data/processed/benchmark_metrics.csv, regenerated by the orchestrator at
    scripts/generators/rebuild_dwf_revision_package.py, which reads
    data/dft_raw/ and scripts/vendor/dwf_plot_config.py. Both are present in
    this package, so the table is reproducible here rather than being a
    committed fixture.

Run from anywhere:
    python3 scripts/figures/fig03_summary_heatmaps.py
"""

from __future__ import annotations

import csv
import os
import sys
from pathlib import Path
from typing import Sequence

BASE_DIR = Path(__file__).resolve().parent
# Every path resolves through scripts/paths.py, the single source of truth
# for this package. Nothing outside the repository root is read or written.
sys.path.insert(0, str(BASE_DIR.parent))
from paths import FIGURES_MAIN, PROCESSED, REPO_ROOT, VERIFICATION_LOGS, ensure_output_dirs  # noqa: E402

CACHE_DIR = VERIFICATION_LOGS / ".cache"
(CACHE_DIR / "matplotlib").mkdir(parents=True, exist_ok=True)
os.environ.setdefault("XDG_CACHE_HOME", str(CACHE_DIR))
os.environ.setdefault("MPLCONFIGDIR", str(CACHE_DIR / "matplotlib"))

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import font_manager


PROJECT_ROOT = REPO_ROOT
BENCHMARK_CSV = PROCESSED / "benchmark_metrics.csv"

# Arial, matching the other manuscript figures. Registering the file makes the
# lookup explicit instead of relying on matplotlib's platform font scan, which
# is what keeps this reproducible off this machine.
ARIAL_FONT_PATH = Path("/System/Library/Fonts/Supplemental/Arial.ttf")
if ARIAL_FONT_PATH.exists():
    font_manager.fontManager.addfont(str(ARIAL_FONT_PATH))
    ARIAL_FONT = font_manager.FontProperties(fname=str(ARIAL_FONT_PATH)).get_name()
else:
    ARIAL_FONT = "Arial"

plt.rcParams.update(
    {
        "font.family": ARIAL_FONT,
        "font.sans-serif": [ARIAL_FONT],
        "mathtext.fontset": "custom",
        "mathtext.rm": ARIAL_FONT,
        "mathtext.it": f"{ARIAL_FONT}:italic",
        "mathtext.bf": f"{ARIAL_FONT}:bold",
        "font.size": 12,
        "axes.titlesize": 14,
        "axes.labelsize": 13,
        "legend.fontsize": 18,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
    }
)

# Method identifiers and display labels (inlined from the orchestrator so this
# script has no python-import dependency on data/rebuild_dwf_revision_package.py).
METHOD_ORDER_MAIN: tuple[str, ...] = (
    "empirical_digitized_reference",
    "elastic_derived_debye",
    "quasi_harmonic_debye",
    "harmonic_phonon_spectrum_isotropic",
)

METHOD_LABELS: dict[str, str] = {
    "empirical_digitized_reference": "empirical\nreference",
    "elastic_derived_debye":         "elastic-derived\nDebye",
    "quasi_harmonic_debye":          "quasi-harmonic\nDebye",
    "harmonic_phonon_spectrum_isotropic": "harmonic phonon\nspectrum (isotropic)",
}

# Mapping from the raw method strings in benchmark_metrics.csv → internal method_id.
# Kept separate from METHOD_LABELS so display labels can be renamed freely.
CSV_METHOD_TO_ID: dict[str, str] = {
    "empirical digitized reference":          "empirical_digitized_reference",
    "elastic-derived Debye":                  "elastic_derived_debye",
    "quasi-harmonic Debye":                   "quasi_harmonic_debye",
    "harmonic phonon spectrum (isotropic)":   "harmonic_phonon_spectrum_isotropic",
}

MATERIAL_KEYS = ["As", "Sb", "Bi_noSOC"]
MATERIAL_DISPLAY = ["As", "Sb", "Bi"]


def format_heatmap_value(value: float, fmt: str) -> str:
    if not np.isfinite(value):
        return "NA"
    return format(float(value), fmt)


def annotate_heatmap(
    ax: plt.Axes,
    matrix: np.ndarray,
    cmap: str,
    *,
    value_fmt: str,
    title: str,
    row_labels: Sequence[str],
    col_labels: Sequence[str],
    cell_text_color: str | None = None,
    invert_contrast: bool = False,
) -> None:
    image = ax.imshow(matrix, aspect="auto", cmap=cmap)
    ax.set_xticks(np.arange(matrix.shape[1]))
    ax.set_yticks(np.arange(matrix.shape[0]))
    ax.set_xticklabels(list(col_labels), rotation=0, fontsize=21)
    ax.set_yticklabels(list(row_labels), fontsize=21)
    for lbl in ax.get_yticklabels():
        lbl.set_multialignment("center")
    ax.tick_params(axis="both", which="both", labelbottom=True, labelleft=True, length=3)
    ax.set_title(title, fontsize=21)

    finite_values = matrix[np.isfinite(matrix)]
    midpoint = float(np.nanmean(finite_values)) if finite_values.size else 0.0
    for row_idx in range(matrix.shape[0]):
        for col_idx in range(matrix.shape[1]):
            value = matrix[row_idx, col_idx]
            if cell_text_color is not None:
                text_color = cell_text_color
            elif invert_contrast:
                # viridis-style: low value = dark cell → white text
                text_color = "white" if (np.isfinite(value) and value < midpoint) else "black"
            else:
                # magma_r / YlOrRd-style: high value = dark cell → white text
                text_color = "white" if (np.isfinite(value) and value > midpoint) else "black"
            ax.text(
                col_idx,
                row_idx,
                format_heatmap_value(float(value), value_fmt),
                ha="center",
                va="center",
                color=text_color,
                fontsize=20,
            )
    cbar = plt.colorbar(image, ax=ax, fraction=0.046, pad=0.03)
    cbar.ax.tick_params(length=3, labelsize=18)


def matrices_from_benchmark_csv(
    csv_path: Path,
    method_order_main: tuple[str, ...],
    method_labels: dict[str, str],
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    values: dict[tuple[str, str], dict[str, float]] = {}
    with csv_path.open("r", encoding="utf-8", newline="") as infile:
        reader = csv.DictReader(infile)
        for row in reader:
            material = row["material"]
            csv_method = row["method"]
            if material not in MATERIAL_KEYS:
                continue
            method_id = CSV_METHOD_TO_ID.get(csv_method)
            if method_id is None:
                continue
            values[(method_id, material)] = {
                "RMSE": float(row["RMSE"]),
                "NRMSE": float(row["NRMSE"]),
                "R2": float(row["R2"]),
            }

    def build(metric: str) -> np.ndarray:
        return np.asarray(
            [[values[(mid, mat)][metric] for mat in MATERIAL_KEYS] for mid in method_order_main],
            dtype=float,
        )

    return build("RMSE"), build("NRMSE"), build("R2")


def plot_summary_heatmaps(
    rmse_matrix: np.ndarray,
    nrmse_matrix: np.ndarray,
    r2_matrix: np.ndarray,
    output_base: Path,
) -> None:
    row_text = [METHOD_LABELS[mid] for mid in METHOD_ORDER_MAIN]
    fig, axes = plt.subplots(1, 3, figsize=(16.0, 6.2), constrained_layout=True)
    annotate_heatmap(
        axes[0],
        rmse_matrix,
        "YlOrRd",
        value_fmt=".3f",
        title=r"RMSE ($\mathrm{\AA}^2$)",
        row_labels=row_text,
        col_labels=MATERIAL_DISPLAY,
    )
    annotate_heatmap(
        axes[1],
        nrmse_matrix,
        "YlOrRd",
        value_fmt=".3f",
        title="NRMSE",
        row_labels=row_text,
        col_labels=MATERIAL_DISPLAY,
    )
    annotate_heatmap(
        axes[2],
        r2_matrix,
        "viridis",
        value_fmt=".3f",
        title=r"$R^2$",
        row_labels=row_text,
        col_labels=MATERIAL_DISPLAY,
        invert_contrast=True,
    )
    for ax in axes[1:]:
        ax.set_yticklabels([])
    fig.savefig(output_base.with_suffix(".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"[fig03] wrote {output_base.with_suffix('.png')}")


def main() -> None:
    ensure_output_dirs()
    if not BENCHMARK_CSV.exists():
        raise FileNotFoundError(
            f"Cannot find benchmark_metrics.csv at {BENCHMARK_CSV}.\n"
            "Regenerate it by running data/rebuild_dwf_revision_package.py "
            "(on a machine where the external raw-calc inputs are reachable)."
        )
    print(f"[fig03] reading {BENCHMARK_CSV}")
    rmse, nrmse, r2 = matrices_from_benchmark_csv(BENCHMARK_CSV, METHOD_ORDER_MAIN, METHOD_LABELS)
    output_base = FIGURES_MAIN / "fig03_summary_heatmaps"
    plot_summary_heatmaps(rmse, nrmse, r2, output_base)


if __name__ == "__main__":
    main()
